//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PhoneApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOSpeler", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    public partial class DTOSpeler : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int GelijkField;
        
        private int GewonnenField;
        
        private int IDField;
        
        private string IsReadyField;
        
        private int LobbyIDField;
        
        private string NickNameField;
        
        private int PuntenField;
        
        private int VerlorenField;
        
        private string WachtwoordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gelijk {
            get {
                return this.GelijkField;
            }
            set {
                if ((this.GelijkField.Equals(value) != true)) {
                    this.GelijkField = value;
                    this.RaisePropertyChanged("Gelijk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gewonnen {
            get {
                return this.GewonnenField;
            }
            set {
                if ((this.GewonnenField.Equals(value) != true)) {
                    this.GewonnenField = value;
                    this.RaisePropertyChanged("Gewonnen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsReady {
            get {
                return this.IsReadyField;
            }
            set {
                if ((object.ReferenceEquals(this.IsReadyField, value) != true)) {
                    this.IsReadyField = value;
                    this.RaisePropertyChanged("IsReady");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyID {
            get {
                return this.LobbyIDField;
            }
            set {
                if ((this.LobbyIDField.Equals(value) != true)) {
                    this.LobbyIDField = value;
                    this.RaisePropertyChanged("LobbyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Punten {
            get {
                return this.PuntenField;
            }
            set {
                if ((this.PuntenField.Equals(value) != true)) {
                    this.PuntenField = value;
                    this.RaisePropertyChanged("Punten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Verloren {
            get {
                return this.VerlorenField;
            }
            set {
                if ((this.VerlorenField.Equals(value) != true)) {
                    this.VerlorenField = value;
                    this.RaisePropertyChanged("Verloren");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wachtwoord {
            get {
                return this.WachtwoordField;
            }
            set {
                if ((object.ReferenceEquals(this.WachtwoordField, value) != true)) {
                    this.WachtwoordField = value;
                    this.RaisePropertyChanged("Wachtwoord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOLobby", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    public partial class DTOLobby : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AantalSpelersField;
        
        private int IDField;
        
        private int MapRowsField;
        
        private string StatusField;
        
        private int TijdField;
        
        private string VormField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AantalSpelers {
            get {
                return this.AantalSpelersField;
            }
            set {
                if ((this.AantalSpelersField.Equals(value) != true)) {
                    this.AantalSpelersField = value;
                    this.RaisePropertyChanged("AantalSpelers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MapRows {
            get {
                return this.MapRowsField;
            }
            set {
                if ((this.MapRowsField.Equals(value) != true)) {
                    this.MapRowsField = value;
                    this.RaisePropertyChanged("MapRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tijd {
            get {
                return this.TijdField;
            }
            set {
                if ((this.TijdField.Equals(value) != true)) {
                    this.TijdField = value;
                    this.RaisePropertyChanged("Tijd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vorm {
            get {
                return this.VormField;
            }
            set {
                if ((object.ReferenceEquals(this.VormField, value) != true)) {
                    this.VormField = value;
                    this.RaisePropertyChanged("Vorm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAllSpelers", ReplyAction="http://tempuri.org/IService1/GetAllSpelersResponse")]
        System.IAsyncResult BeginGetAllSpelers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler> EndGetAllSpelers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddSpeler", ReplyAction="http://tempuri.org/IService1/AddSpelerResponse")]
        System.IAsyncResult BeginAddSpeler(string name, string pass, System.AsyncCallback callback, object asyncState);
        
        void EndAddSpeler(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddLobby", ReplyAction="http://tempuri.org/IService1/AddLobbyResponse")]
        System.IAsyncResult BeginAddLobby(System.AsyncCallback callback, object asyncState);
        
        void EndAddLobby(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAllLobbies", ReplyAction="http://tempuri.org/IService1/GetAllLobbiesResponse")]
        System.IAsyncResult BeginGetAllLobbies(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby> EndGetAllLobbies(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/JoinLobby", ReplyAction="http://tempuri.org/IService1/JoinLobbyResponse")]
        System.IAsyncResult BeginJoinLobby(int lobbyID, int spelerID, System.AsyncCallback callback, object asyncState);
        
        void EndJoinLobby(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/MakeMap", ReplyAction="http://tempuri.org/IService1/MakeMapResponse")]
        System.IAsyncResult BeginMakeMap(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>> EndMakeMap(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/MakeGrid", ReplyAction="http://tempuri.org/IService1/MakeGridResponse")]
        System.IAsyncResult BeginMakeGrid(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<int> EndMakeGrid(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/OpzetFase", ReplyAction="http://tempuri.org/IService1/OpzetFaseResponse")]
        System.IAsyncResult BeginOpzetFase(System.AsyncCallback callback, object asyncState);
        
        bool EndOpzetFase(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ChanceOpzetFase", ReplyAction="http://tempuri.org/IService1/ChanceOpzetFaseResponse")]
        System.IAsyncResult BeginChanceOpzetFase(System.AsyncCallback callback, object asyncState);
        
        bool EndChanceOpzetFase(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SetOpzetFase", ReplyAction="http://tempuri.org/IService1/SetOpzetFaseResponse")]
        System.IAsyncResult BeginSetOpzetFase(System.AsyncCallback callback, object asyncState);
        
        bool EndSetOpzetFase(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GameState", ReplyAction="http://tempuri.org/IService1/GameStateResponse")]
        System.IAsyncResult BeginGameState(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGameState(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(PhoneApp1.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PhoneApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllSpelersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllSpelersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllLobbiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllLobbiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MakeMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MakeMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MakeGridCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MakeGridCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpzetFaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public OpzetFaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChanceOpzetFaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChanceOpzetFaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetOpzetFaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetOpzetFaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GameStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhoneApp1.ServiceReference1.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhoneApp1.ServiceReference1.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PhoneApp1.ServiceReference1.IService1>, PhoneApp1.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetAllSpelersDelegate;
        
        private EndOperationDelegate onEndGetAllSpelersDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllSpelersCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddSpelerDelegate;
        
        private EndOperationDelegate onEndAddSpelerDelegate;
        
        private System.Threading.SendOrPostCallback onAddSpelerCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddLobbyDelegate;
        
        private EndOperationDelegate onEndAddLobbyDelegate;
        
        private System.Threading.SendOrPostCallback onAddLobbyCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllLobbiesDelegate;
        
        private EndOperationDelegate onEndGetAllLobbiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllLobbiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginJoinLobbyDelegate;
        
        private EndOperationDelegate onEndJoinLobbyDelegate;
        
        private System.Threading.SendOrPostCallback onJoinLobbyCompletedDelegate;
        
        private BeginOperationDelegate onBeginMakeMapDelegate;
        
        private EndOperationDelegate onEndMakeMapDelegate;
        
        private System.Threading.SendOrPostCallback onMakeMapCompletedDelegate;
        
        private BeginOperationDelegate onBeginMakeGridDelegate;
        
        private EndOperationDelegate onEndMakeGridDelegate;
        
        private System.Threading.SendOrPostCallback onMakeGridCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpzetFaseDelegate;
        
        private EndOperationDelegate onEndOpzetFaseDelegate;
        
        private System.Threading.SendOrPostCallback onOpzetFaseCompletedDelegate;
        
        private BeginOperationDelegate onBeginChanceOpzetFaseDelegate;
        
        private EndOperationDelegate onEndChanceOpzetFaseDelegate;
        
        private System.Threading.SendOrPostCallback onChanceOpzetFaseCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetOpzetFaseDelegate;
        
        private EndOperationDelegate onEndSetOpzetFaseDelegate;
        
        private System.Threading.SendOrPostCallback onSetOpzetFaseCompletedDelegate;
        
        private BeginOperationDelegate onBeginGameStateDelegate;
        
        private EndOperationDelegate onEndGameStateDelegate;
        
        private System.Threading.SendOrPostCallback onGameStateCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllSpelersCompletedEventArgs> GetAllSpelersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddSpelerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddLobbyCompleted;
        
        public event System.EventHandler<GetAllLobbiesCompletedEventArgs> GetAllLobbiesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> JoinLobbyCompleted;
        
        public event System.EventHandler<MakeMapCompletedEventArgs> MakeMapCompleted;
        
        public event System.EventHandler<MakeGridCompletedEventArgs> MakeGridCompleted;
        
        public event System.EventHandler<OpzetFaseCompletedEventArgs> OpzetFaseCompleted;
        
        public event System.EventHandler<ChanceOpzetFaseCompletedEventArgs> ChanceOpzetFaseCompleted;
        
        public event System.EventHandler<SetOpzetFaseCompletedEventArgs> SetOpzetFaseCompleted;
        
        public event System.EventHandler<GameStateCompletedEventArgs> GameStateCompleted;
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginGetAllSpelers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllSpelers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler> PhoneApp1.ServiceReference1.IService1.EndGetAllSpelers(System.IAsyncResult result) {
            return base.Channel.EndGetAllSpelers(result);
        }
        
        private System.IAsyncResult OnBeginGetAllSpelers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginGetAllSpelers(callback, asyncState);
        }
        
        private object[] OnEndGetAllSpelers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler> retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndGetAllSpelers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllSpelersCompleted(object state) {
            if ((this.GetAllSpelersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllSpelersCompleted(this, new GetAllSpelersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllSpelersAsync() {
            this.GetAllSpelersAsync(null);
        }
        
        public void GetAllSpelersAsync(object userState) {
            if ((this.onBeginGetAllSpelersDelegate == null)) {
                this.onBeginGetAllSpelersDelegate = new BeginOperationDelegate(this.OnBeginGetAllSpelers);
            }
            if ((this.onEndGetAllSpelersDelegate == null)) {
                this.onEndGetAllSpelersDelegate = new EndOperationDelegate(this.OnEndGetAllSpelers);
            }
            if ((this.onGetAllSpelersCompletedDelegate == null)) {
                this.onGetAllSpelersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllSpelersCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllSpelersDelegate, null, this.onEndGetAllSpelersDelegate, this.onGetAllSpelersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginAddSpeler(string name, string pass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddSpeler(name, pass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.ServiceReference1.IService1.EndAddSpeler(System.IAsyncResult result) {
            base.Channel.EndAddSpeler(result);
        }
        
        private System.IAsyncResult OnBeginAddSpeler(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            string pass = ((string)(inValues[1]));
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginAddSpeler(name, pass, callback, asyncState);
        }
        
        private object[] OnEndAddSpeler(System.IAsyncResult result) {
            ((PhoneApp1.ServiceReference1.IService1)(this)).EndAddSpeler(result);
            return null;
        }
        
        private void OnAddSpelerCompleted(object state) {
            if ((this.AddSpelerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddSpelerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddSpelerAsync(string name, string pass) {
            this.AddSpelerAsync(name, pass, null);
        }
        
        public void AddSpelerAsync(string name, string pass, object userState) {
            if ((this.onBeginAddSpelerDelegate == null)) {
                this.onBeginAddSpelerDelegate = new BeginOperationDelegate(this.OnBeginAddSpeler);
            }
            if ((this.onEndAddSpelerDelegate == null)) {
                this.onEndAddSpelerDelegate = new EndOperationDelegate(this.OnEndAddSpeler);
            }
            if ((this.onAddSpelerCompletedDelegate == null)) {
                this.onAddSpelerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddSpelerCompleted);
            }
            base.InvokeAsync(this.onBeginAddSpelerDelegate, new object[] {
                        name,
                        pass}, this.onEndAddSpelerDelegate, this.onAddSpelerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginAddLobby(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddLobby(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.ServiceReference1.IService1.EndAddLobby(System.IAsyncResult result) {
            base.Channel.EndAddLobby(result);
        }
        
        private System.IAsyncResult OnBeginAddLobby(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginAddLobby(callback, asyncState);
        }
        
        private object[] OnEndAddLobby(System.IAsyncResult result) {
            ((PhoneApp1.ServiceReference1.IService1)(this)).EndAddLobby(result);
            return null;
        }
        
        private void OnAddLobbyCompleted(object state) {
            if ((this.AddLobbyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddLobbyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddLobbyAsync() {
            this.AddLobbyAsync(null);
        }
        
        public void AddLobbyAsync(object userState) {
            if ((this.onBeginAddLobbyDelegate == null)) {
                this.onBeginAddLobbyDelegate = new BeginOperationDelegate(this.OnBeginAddLobby);
            }
            if ((this.onEndAddLobbyDelegate == null)) {
                this.onEndAddLobbyDelegate = new EndOperationDelegate(this.OnEndAddLobby);
            }
            if ((this.onAddLobbyCompletedDelegate == null)) {
                this.onAddLobbyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddLobbyCompleted);
            }
            base.InvokeAsync(this.onBeginAddLobbyDelegate, null, this.onEndAddLobbyDelegate, this.onAddLobbyCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginGetAllLobbies(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllLobbies(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby> PhoneApp1.ServiceReference1.IService1.EndGetAllLobbies(System.IAsyncResult result) {
            return base.Channel.EndGetAllLobbies(result);
        }
        
        private System.IAsyncResult OnBeginGetAllLobbies(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginGetAllLobbies(callback, asyncState);
        }
        
        private object[] OnEndGetAllLobbies(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby> retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndGetAllLobbies(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllLobbiesCompleted(object state) {
            if ((this.GetAllLobbiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllLobbiesCompleted(this, new GetAllLobbiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllLobbiesAsync() {
            this.GetAllLobbiesAsync(null);
        }
        
        public void GetAllLobbiesAsync(object userState) {
            if ((this.onBeginGetAllLobbiesDelegate == null)) {
                this.onBeginGetAllLobbiesDelegate = new BeginOperationDelegate(this.OnBeginGetAllLobbies);
            }
            if ((this.onEndGetAllLobbiesDelegate == null)) {
                this.onEndGetAllLobbiesDelegate = new EndOperationDelegate(this.OnEndGetAllLobbies);
            }
            if ((this.onGetAllLobbiesCompletedDelegate == null)) {
                this.onGetAllLobbiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllLobbiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllLobbiesDelegate, null, this.onEndGetAllLobbiesDelegate, this.onGetAllLobbiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginJoinLobby(int lobbyID, int spelerID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginJoinLobby(lobbyID, spelerID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.ServiceReference1.IService1.EndJoinLobby(System.IAsyncResult result) {
            base.Channel.EndJoinLobby(result);
        }
        
        private System.IAsyncResult OnBeginJoinLobby(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int lobbyID = ((int)(inValues[0]));
            int spelerID = ((int)(inValues[1]));
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginJoinLobby(lobbyID, spelerID, callback, asyncState);
        }
        
        private object[] OnEndJoinLobby(System.IAsyncResult result) {
            ((PhoneApp1.ServiceReference1.IService1)(this)).EndJoinLobby(result);
            return null;
        }
        
        private void OnJoinLobbyCompleted(object state) {
            if ((this.JoinLobbyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.JoinLobbyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void JoinLobbyAsync(int lobbyID, int spelerID) {
            this.JoinLobbyAsync(lobbyID, spelerID, null);
        }
        
        public void JoinLobbyAsync(int lobbyID, int spelerID, object userState) {
            if ((this.onBeginJoinLobbyDelegate == null)) {
                this.onBeginJoinLobbyDelegate = new BeginOperationDelegate(this.OnBeginJoinLobby);
            }
            if ((this.onEndJoinLobbyDelegate == null)) {
                this.onEndJoinLobbyDelegate = new EndOperationDelegate(this.OnEndJoinLobby);
            }
            if ((this.onJoinLobbyCompletedDelegate == null)) {
                this.onJoinLobbyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnJoinLobbyCompleted);
            }
            base.InvokeAsync(this.onBeginJoinLobbyDelegate, new object[] {
                        lobbyID,
                        spelerID}, this.onEndJoinLobbyDelegate, this.onJoinLobbyCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginMakeMap(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMakeMap(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>> PhoneApp1.ServiceReference1.IService1.EndMakeMap(System.IAsyncResult result) {
            return base.Channel.EndMakeMap(result);
        }
        
        private System.IAsyncResult OnBeginMakeMap(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginMakeMap(callback, asyncState);
        }
        
        private object[] OnEndMakeMap(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>> retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndMakeMap(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMakeMapCompleted(object state) {
            if ((this.MakeMapCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MakeMapCompleted(this, new MakeMapCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MakeMapAsync() {
            this.MakeMapAsync(null);
        }
        
        public void MakeMapAsync(object userState) {
            if ((this.onBeginMakeMapDelegate == null)) {
                this.onBeginMakeMapDelegate = new BeginOperationDelegate(this.OnBeginMakeMap);
            }
            if ((this.onEndMakeMapDelegate == null)) {
                this.onEndMakeMapDelegate = new EndOperationDelegate(this.OnEndMakeMap);
            }
            if ((this.onMakeMapCompletedDelegate == null)) {
                this.onMakeMapCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMakeMapCompleted);
            }
            base.InvokeAsync(this.onBeginMakeMapDelegate, null, this.onEndMakeMapDelegate, this.onMakeMapCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginMakeGrid(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMakeGrid(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<int> PhoneApp1.ServiceReference1.IService1.EndMakeGrid(System.IAsyncResult result) {
            return base.Channel.EndMakeGrid(result);
        }
        
        private System.IAsyncResult OnBeginMakeGrid(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginMakeGrid(callback, asyncState);
        }
        
        private object[] OnEndMakeGrid(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<int> retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndMakeGrid(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMakeGridCompleted(object state) {
            if ((this.MakeGridCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MakeGridCompleted(this, new MakeGridCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MakeGridAsync() {
            this.MakeGridAsync(null);
        }
        
        public void MakeGridAsync(object userState) {
            if ((this.onBeginMakeGridDelegate == null)) {
                this.onBeginMakeGridDelegate = new BeginOperationDelegate(this.OnBeginMakeGrid);
            }
            if ((this.onEndMakeGridDelegate == null)) {
                this.onEndMakeGridDelegate = new EndOperationDelegate(this.OnEndMakeGrid);
            }
            if ((this.onMakeGridCompletedDelegate == null)) {
                this.onMakeGridCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMakeGridCompleted);
            }
            base.InvokeAsync(this.onBeginMakeGridDelegate, null, this.onEndMakeGridDelegate, this.onMakeGridCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginOpzetFase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginOpzetFase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool PhoneApp1.ServiceReference1.IService1.EndOpzetFase(System.IAsyncResult result) {
            return base.Channel.EndOpzetFase(result);
        }
        
        private System.IAsyncResult OnBeginOpzetFase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginOpzetFase(callback, asyncState);
        }
        
        private object[] OnEndOpzetFase(System.IAsyncResult result) {
            bool retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndOpzetFase(result);
            return new object[] {
                    retVal};
        }
        
        private void OnOpzetFaseCompleted(object state) {
            if ((this.OpzetFaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpzetFaseCompleted(this, new OpzetFaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpzetFaseAsync() {
            this.OpzetFaseAsync(null);
        }
        
        public void OpzetFaseAsync(object userState) {
            if ((this.onBeginOpzetFaseDelegate == null)) {
                this.onBeginOpzetFaseDelegate = new BeginOperationDelegate(this.OnBeginOpzetFase);
            }
            if ((this.onEndOpzetFaseDelegate == null)) {
                this.onEndOpzetFaseDelegate = new EndOperationDelegate(this.OnEndOpzetFase);
            }
            if ((this.onOpzetFaseCompletedDelegate == null)) {
                this.onOpzetFaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpzetFaseCompleted);
            }
            base.InvokeAsync(this.onBeginOpzetFaseDelegate, null, this.onEndOpzetFaseDelegate, this.onOpzetFaseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginChanceOpzetFase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChanceOpzetFase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool PhoneApp1.ServiceReference1.IService1.EndChanceOpzetFase(System.IAsyncResult result) {
            return base.Channel.EndChanceOpzetFase(result);
        }
        
        private System.IAsyncResult OnBeginChanceOpzetFase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginChanceOpzetFase(callback, asyncState);
        }
        
        private object[] OnEndChanceOpzetFase(System.IAsyncResult result) {
            bool retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndChanceOpzetFase(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChanceOpzetFaseCompleted(object state) {
            if ((this.ChanceOpzetFaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChanceOpzetFaseCompleted(this, new ChanceOpzetFaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChanceOpzetFaseAsync() {
            this.ChanceOpzetFaseAsync(null);
        }
        
        public void ChanceOpzetFaseAsync(object userState) {
            if ((this.onBeginChanceOpzetFaseDelegate == null)) {
                this.onBeginChanceOpzetFaseDelegate = new BeginOperationDelegate(this.OnBeginChanceOpzetFase);
            }
            if ((this.onEndChanceOpzetFaseDelegate == null)) {
                this.onEndChanceOpzetFaseDelegate = new EndOperationDelegate(this.OnEndChanceOpzetFase);
            }
            if ((this.onChanceOpzetFaseCompletedDelegate == null)) {
                this.onChanceOpzetFaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChanceOpzetFaseCompleted);
            }
            base.InvokeAsync(this.onBeginChanceOpzetFaseDelegate, null, this.onEndChanceOpzetFaseDelegate, this.onChanceOpzetFaseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginSetOpzetFase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetOpzetFase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool PhoneApp1.ServiceReference1.IService1.EndSetOpzetFase(System.IAsyncResult result) {
            return base.Channel.EndSetOpzetFase(result);
        }
        
        private System.IAsyncResult OnBeginSetOpzetFase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginSetOpzetFase(callback, asyncState);
        }
        
        private object[] OnEndSetOpzetFase(System.IAsyncResult result) {
            bool retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndSetOpzetFase(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetOpzetFaseCompleted(object state) {
            if ((this.SetOpzetFaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetOpzetFaseCompleted(this, new SetOpzetFaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetOpzetFaseAsync() {
            this.SetOpzetFaseAsync(null);
        }
        
        public void SetOpzetFaseAsync(object userState) {
            if ((this.onBeginSetOpzetFaseDelegate == null)) {
                this.onBeginSetOpzetFaseDelegate = new BeginOperationDelegate(this.OnBeginSetOpzetFase);
            }
            if ((this.onEndSetOpzetFaseDelegate == null)) {
                this.onEndSetOpzetFaseDelegate = new EndOperationDelegate(this.OnEndSetOpzetFase);
            }
            if ((this.onSetOpzetFaseCompletedDelegate == null)) {
                this.onSetOpzetFaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetOpzetFaseCompleted);
            }
            base.InvokeAsync(this.onBeginSetOpzetFaseDelegate, null, this.onEndSetOpzetFaseDelegate, this.onSetOpzetFaseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginGameState(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGameState(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> PhoneApp1.ServiceReference1.IService1.EndGameState(System.IAsyncResult result) {
            return base.Channel.EndGameState(result);
        }
        
        private System.IAsyncResult OnBeginGameState(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginGameState(callback, asyncState);
        }
        
        private object[] OnEndGameState(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndGameState(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGameStateCompleted(object state) {
            if ((this.GameStateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GameStateCompleted(this, new GameStateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GameStateAsync() {
            this.GameStateAsync(null);
        }
        
        public void GameStateAsync(object userState) {
            if ((this.onBeginGameStateDelegate == null)) {
                this.onBeginGameStateDelegate = new BeginOperationDelegate(this.OnBeginGameState);
            }
            if ((this.onEndGameStateDelegate == null)) {
                this.onEndGameStateDelegate = new EndOperationDelegate(this.OnEndGameState);
            }
            if ((this.onGameStateCompletedDelegate == null)) {
                this.onGameStateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGameStateCompleted);
            }
            base.InvokeAsync(this.onBeginGameStateDelegate, null, this.onEndGameStateDelegate, this.onGameStateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PhoneApp1.ServiceReference1.IService1.EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int value = ((int)(inValues[0]));
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(int value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginGetDataUsingDataContract(PhoneApp1.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.ServiceReference1.CompositeType PhoneApp1.ServiceReference1.IService1.EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneApp1.ServiceReference1.CompositeType composite = ((PhoneApp1.ServiceReference1.CompositeType)(inValues[0]));
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            PhoneApp1.ServiceReference1.CompositeType retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(PhoneApp1.ServiceReference1.CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(PhoneApp1.ServiceReference1.CompositeType composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneApp1.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<PhoneApp1.ServiceReference1.IService1>, PhoneApp1.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<PhoneApp1.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllSpelers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllSpelers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler> EndGetAllSpelers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOSpeler>)(base.EndInvoke("GetAllSpelers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddSpeler(string name, string pass, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = name;
                _args[1] = pass;
                System.IAsyncResult _result = base.BeginInvoke("AddSpeler", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddSpeler(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddSpeler", _args, result);
            }
            
            public System.IAsyncResult BeginAddLobby(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("AddLobby", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddLobby(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddLobby", _args, result);
            }
            
            public System.IAsyncResult BeginGetAllLobbies(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllLobbies", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby> EndGetAllLobbies(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.DTOLobby>)(base.EndInvoke("GetAllLobbies", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginJoinLobby(int lobbyID, int spelerID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = lobbyID;
                _args[1] = spelerID;
                System.IAsyncResult _result = base.BeginInvoke("JoinLobby", _args, callback, asyncState);
                return _result;
            }
            
            public void EndJoinLobby(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("JoinLobby", _args, result);
            }
            
            public System.IAsyncResult BeginMakeMap(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("MakeMap", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>> EndMakeMap(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>> _result = ((System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<int>>)(base.EndInvoke("MakeMap", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginMakeGrid(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("MakeGrid", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<int> EndMakeGrid(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<int> _result = ((System.Collections.ObjectModel.ObservableCollection<int>)(base.EndInvoke("MakeGrid", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginOpzetFase(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("OpzetFase", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndOpzetFase(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("OpzetFase", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChanceOpzetFase(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ChanceOpzetFase", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndChanceOpzetFase(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ChanceOpzetFase", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetOpzetFase(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SetOpzetFase", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSetOpzetFase(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SetOpzetFase", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGameState(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GameState", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGameState(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GameState", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = value;
                System.IAsyncResult _result = base.BeginInvoke("GetData", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetData(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDataUsingDataContract(PhoneApp1.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = composite;
                System.IAsyncResult _result = base.BeginInvoke("GetDataUsingDataContract", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.ServiceReference1.CompositeType _result = ((PhoneApp1.ServiceReference1.CompositeType)(base.EndInvoke("GetDataUsingDataContract", _args, result)));
                return _result;
            }
        }
    }
}
